apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world1
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world1
  template:
    metadata:
      labels:
        app: hello-world1
    spec:
      containers:
      - name: hello-world1
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 8080

