apiVersion: apps/v1
kind: Deployment
metadata:
  name: try123
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: try123
  template:
    metadata:
      labels:
        app: try123
    spec:
      containers:
      - name: try123
        image: k8s.gcr.io/echoserver:1.4
        ports:
        - containerPort: 8080

